# This YAML configuration file defines the schema for a vehicle insurance dataset.
# It specifies the data types for each column, categorizes columns into numerical and categorical types,
# identifies columns to be dropped, and lists features for data transformation.
# Additionally, it includes columns for min-max scaling.
columns:
  - id: int
  - Gender: category
  - Age: int
  - Driving_License: int
  - Region_Code: float
  - Previously_Insured: int
  - Vehicle_Age: category
  - Vehicle_Damage: category
  - Annual_Premium: float
  - Policy_Sales_Channel: float
  - Vintage: int
  - Response: int

numerical_columns:
  - Age
  - Driving_License
  - Region_Code
  - Previously_Insured
  - Annual_Premium
  - Policy_Sales_Channel
  - Vintage
  - Response

categorical_columns:
  - Gender
  - Vehicle_Age
  - Vehicle_Damage

drop_columns: _id

# for data transformation
num_features:
  - Age
  - Vintage

mm_columns:
  - Annual_Premium
